import { Card, Card2, Card3, Card4 } from "components/card";
import { FilterCategory } from "components/filter";
import { LayoutHome } from "layouts";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <div className="layout-container">
          <div className="py-8">
            <FilterCategory />
          </div>
          <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
            <div className="flex flex-col gap-5">
              <Card />
              <Card4 />
            </div>
            <div className="flex flex-col gap-5">
              <Card2 />
              <Card3 />
            </div>
            <div className="flex flex-col gap-5">
              <Card3 />
              <Card2 />
            </div>
            <div className="flex flex-col gap-5">
              <Card4 />
              <Card />
            </div>
          </div>
        </div>
      </LayoutHome>
    </>
  );
};

export default Home;
