import { Card } from "components/card";
import { Switch } from "components/checkbox";
import { LayoutGird2 } from "components/common";
import { FormSignIn, FormSignUp } from "components/form";
import { Input } from "components/input";
import Head from "next/head";
import styled from "styled-components";

const StyledHomePage = styled.div`
  main {
    margin-top: 40px;
  }
`;

export default function Home() {
  return (
    <StyledHomePage>
      <Head>
        <title>Faster UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="layout-container">
        <LayoutGird2>
          <div className="grid-layout">
            <div className="grid-column">
              <Switch />
              <FormSignUp />
            </div>
            <div className="grid-column">
              <Card />
              <Input />
            </div>
            <div className="grid-column">
              <FormSignIn />
            </div>
          </div>
        </LayoutGird2>
      </main>
    </StyledHomePage>
  );
}
