import axios from "axios";
import LayoutHome from "layouts/LayoutHome";
import { HomeBanner } from "modules/home";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = ({ data }: any) => {
  console.log("data: ", data);
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <div className="max-w-[1030px] py-[15px] bg-[#f9f9f9] mx-auto">
          <HomeBanner />
        </div>
      </LayoutHome>
    </>
  );
};

export async function getInitialProps() {
  const { data } = await axios.get("/api/home");
  return {
    props: { data },
  };
}

export default Home;
